### ISSUE TITLE
Integration with Unity IAP 3.2.2

### ISSUE THREAD

**Issue by imurashka** [RevenueCat/purchases-unity#58]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-unity/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-unity/issues)

1. Environment
   - Platform: Android
   - SDK version: 3.2
   - OS + version: 7.1.2
   - Xcode/Android Studio version: N/A
   - Unity IAP: 3.2.2 and 4.0.0 (tried both)
   - Unity version: 2020.3.11f1- 
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue: [RC-Fatal.log](https://github.com/RevenueCat/purchases-unity/files/7001166/RC-Fatal.log)
3. Steps to reproduce, with a description of expected vs. actual behavior: see below
4. I have followed [documentation](https://docs.revenuecat.com/docs/unity) to integrate RevenueCat alongside with Unity IAP and faced with fatal error on Android on startup:
```
FATAL EXCEPTION: Thread-8
Process: MY_PACKAGE_NAME, PID: 30996
java.lang.Error: FATAL EXCEPTION [Thread-8]
Unity version : 2020.3.11f1
Device model : samsung SM-G973N
Device fingerprint: samsung/beyond1qlteue/beyond1q:7.1.2/PPR1.190810.011/700210126:user/release-keys
Build Type : Release
Scripting Backend : Mono
ABI : armeabi-v7a
Strip Engine Code : false

Caused by: java.lang.NoSuchMethodError: No virtual method getSkus()Ljava/util/ArrayList; in class Lcom/android/billingclient/api/Purchase; or its super classes (declaration of 'com.android.billingclient.api.Purchase' appears in /data/app/MY_PACKAGE_NAME-1/base.apk)
	at com.revenuecat.purchases.google.PurchaseDetailsConversionsKt.toRevenueCatPurchaseDetails(purchaseDetailsConversions.kt:16)
	at com.revenuecat.purchases.google.BillingWrapper.toMapOfGooglePurchaseWrapper(BillingWrapper.kt:404)
	at com.revenuecat.purchases.google.BillingWrapper.access$toMapOfGooglePurchaseWrapper(BillingWrapper.kt:51)
	at com.revenuecat.purchases.google.BillingWrapper$queryPurchases$1.invoke(BillingWrapper.kt:393)
	at com.revenuecat.purchases.google.BillingWrapper$queryPurchases$1.invoke(BillingWrapper.kt:51)
	at com.revenuecat.purchases.google.BillingWrapper.withConnectedClient(BillingWrapper.kt:567)
	at com.revenuecat.purchases.google.BillingWrapper.queryPurchases(BillingWrapper.kt:366)
	at com.revenuecat.purchases.Purchases$updatePendingPurchaseQueue$1.run(Purchases.kt:1692)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```
I tried to integrate it into an empty project - only the `Purchases` component on scene with my `Revenue Cat API Key` and custom `App User ID`. The result is the same - fatal error. Interesting observation - I don't have this issue when I use incorrect android package name (anything else but not my real package name).
Not sure, but probably it is related to https://github.com/RevenueCat/purchases-android/pull/302

**Comment by vegaro** [comment]
Thanks for opening @imurashka . What's causing this is that IAP 3.2.2 is using BillingClient 3.x.x and the latest version of our plugin uses BillingClient 4.x.x.

It's strange though that you are using the version https://github.com/RevenueCat/purchases-unity/releases/tag/3.2.0 of our plugin. Can you make sure that's the version you're using? It should be compatible since that version still uses BillingClient 3.x.x and it shouldn't be calling `getSkus()` at all.

**Comment by imurashka** [comment]
Well, I am definitely not using the link form on the github release page :) I am using the [package](https://github.com/RevenueCat/purchases-unity/files/7001616/Purchases-from-docs.zip)
 from the [documentation](https://docs.revenuecat.com/docs/unity) page. Just checked your link and it works. Do you have outdated docs?

**Comment by imurashka** [comment]
Hello @vegaro! Thank you for quick response! 
Well, I am definitely not using the link form on the github release page :) I am using the [package](https://github.com/RevenueCat/purchases-unity/files/7001616/Purchases-from-docs.zip)
 from the [documentation](https://docs.revenuecat.com/docs/unity) page. Just checked your link and it works. Do you have outdated docs?

**Comment by vegaro** [comment]
That's a good point. I will make sure the docs get updated to indicate the latest version of the plugin compatible with Unity IAP 4.0.0 is 3.2.0. 

Hopefully Unity updates to the more recent BillingClient soon so that the latest versions of the plugin can be used.

I will close this issue since it's more related with Unity IAP using an outdated version of the BillingClient.
