### ISSUE TITLE
Game Crashes on Start (Android)

### ISSUE THREAD

**Issue by YigitVeloxia** [RevenueCat/purchases-unity#67]
- [x] I have updated Purchases SDK to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-unity/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-unity/issues)

**Describe the bug**
Game crashes on start with the following exception:
```
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime Process: com.veloxia.spacecolonyidle, PID: 27870
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime java.lang.NoSuchMethodError: No virtual method getSkus()Ljava/util/ArrayList; in class Lcom/android/billingclient/api/Purchase; or its super classes (declaration of 'com.android.billingclient.api.Purchase' appears in /data/app/~~fnfgVdGI4x2J-NcOPxLRew==/com.veloxia.spacecolonyidle-mj2NueCnx7pHNpxdwK-Xuw==/base.apk)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at com.revenuecat.purchases.google.PurchaseDetailsConversionsKt.toRevenueCatPurchaseDetails(purchaseDetailsConversions.kt:16)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at com.revenuecat.purchases.google.BillingWrapper.toMapOfGooglePurchaseWrapper(BillingWrapper.kt:404)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at com.revenuecat.purchases.google.BillingWrapper.access$toMapOfGooglePurchaseWrapper(BillingWrapper.kt:51)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at com.revenuecat.purchases.google.BillingWrapper$queryPurchases$1.invoke(BillingWrapper.kt:393)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at com.revenuecat.purchases.google.BillingWrapper$queryPurchases$1.invoke(BillingWrapper.kt:51)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at com.revenuecat.purchases.google.BillingWrapper.withConnectedClient(BillingWrapper.kt:571)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at com.revenuecat.purchases.google.BillingWrapper.queryPurchases(BillingWrapper.kt:366)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at com.revenuecat.purchases.Purchases$updatePendingPurchaseQueue$1.run(Purchases.kt:1692)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021/09/14 12:18:14.984 27870 28344 Error AndroidRuntime     at java.lang.Thread.run(Thread.java:923)
```

1. Environment
   1. Platform: Android
   2. SDK version: 3.4.1
   3. OS + version: Android 11
   4. Xcode/Android Studio version:
   5. Unity version: 2020.3.18f1
   6. How widespread is the issue. Percentage of devices affected. 100%

We are using Unity Purchases with RevenueCat. RevenueCat will only be used for logging purposes.

Related:
https://community.revenuecat.com/sdks-51/android-subscription-crashes-after-test-purchase-363

**Comment by vegaro** [comment]
I am sorry about the issues. This is due to an incompatibility between the latest version of our plugin and Unity IAP. They need to update one of their dependencies. Until then, you have to use a previous version of our plugin (3.2.0)

If you want to read more about it, someone opened the same issue one month ago https://github.com/RevenueCat/purchases-unity/issues/58
