### ISSUE TITLE
3.5.0 Version NoSuchMethodError getSkus()

### ISSUE THREAD

**Issue by ausatovappcraft** [RevenueCat/purchases-unity#75]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-unity/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-unity/issues)

Hello, we have a trouble with the latest version 3.5.0 when starting app
Unity version 

1. Environment
   1. Platform: Android
   2. SDK version: 3.5.0
   3. OS + version: any android
   4. Xcode/Android Studio version:
   5. Unity version: 2020.3.24f1
   6. How widespread is the issue. Percentage of devices affected. 100% when no ads was bought
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
/AndroidRuntime: FATAL EXCEPTION: Thread-35
    Process: tower.defence.merge.game, PID: 6756
    java.lang.NoSuchMethodError: No virtual method getSkus()Ljava/util/ArrayList; in class Lcom/android/billingclient/api/Purchase; or its super classes (declaration of 'com.android.billingclient.api.Purchase' appears in /data/app/~~DnMFn1uQiR_J7Wpdy2btBw==/tower.defence.merge.game-fDY9Su4YPJeSDype-6AO0g==/base.apk)
        at com.revenuecat.purchases.google.PurchaseDetailsConversionsKt.toRevenueCatPurchaseDetails(purchaseDetailsConversions.kt:16)
        at com.revenuecat.purchases.google.BillingWrapper.toMapOfGooglePurchaseWrapper(BillingWrapper.kt:418)
        at com.revenuecat.purchases.google.BillingWrapper.access$toMapOfGooglePurchaseWrapper(BillingWrapper.kt:53)
        at com.revenuecat.purchases.google.BillingWrapper$queryPurchases$1.invoke(BillingWrapper.kt:407)
        at com.revenuecat.purchases.google.BillingWrapper$queryPurchases$1.invoke(BillingWrapper.kt:53)
        at com.revenuecat.purchases.google.BillingWrapper.withConnectedClient(BillingWrapper.kt:593)
        at com.revenuecat.purchases.google.BillingWrapper.queryPurchases(BillingWrapper.kt:380)
        at com.revenuecat.purchases.Purchases$updatePendingPurchaseQueue$1.run(Purchases.kt:1707)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
3. Launch the app

Can u help ? :)

Thanks

**Comment by codykerns** [comment]
Hey @ausatovappcraft! The method `getSkus` was added in BillingClient 4.0.0 - do you also use Unity IAP? It's possible it could be using a conflicting version of BillingClient that's causing this error.

**Comment by ausatovappcraft** [comment]
Thank you for the fast answer @codykerns 
Yes, we're using Unity IAP
And i just checked our mainTemplate.gradle.. we have these lines there 

`// Android Resolver Dependencies End
**DEPS**
    configurations.all {
        exclude group: 'com.android.billingclient', module: 'billing'
    }
}
`
Should we remove these lines?

**Comment by codykerns** [comment]
@ausatovappcraft do you need to use Unity IAP? If so, our docs mention to stay on SDK 3.2.0 until Unity IAP is updated to support BillingClient 4.0.0: https://docs.revenuecat.com/docs/unity#installation-with-unity-iap-side-by-side

If you don't need Unity IAP, you should be safe to remove it and stay on 3.5.0 - does that make sense?

**Comment by ausatovappcraft** [comment]
Yes, we need Unity IAP
Thank you for help!
